node {
   def mvnHome
   stage('Build') { // for display purposes
      // Get some code from a GitHub repository
     
   }
   stage('SonarQube analysis') {
    withSonarQubeEnv('My SonarQube Server') {
      // requires SonarQube Scanner for Maven 3.2+
      sh 'mvn org.sonarsource.scanner.maven:sonar-maven-plugin:3.2:sonar'
    }
  }
   stage('Unit Test') {
      // Run the maven build
     
   }
   stage('Archival') {
     
   }
    stage('Dev to Deploy') {
     
   } 
  
   stage('Production') {
     
   }
}
